### PR TITLE
mruby: Make Ruby detectable

### PR DESCRIPTION
**Pull request by RobLoach**
Have Ruby default to enabled, only if it's available.

@remi6397 Something like this perhaps? Adding Ruby as a dependency to build TIC-80 is a big ask. While Ruby could be available on many systems, it unfortunately won't be available on ALL systems. Having it fallback could help.

RE: https://github.com/nesbox/TIC-80/pull/1006

### CODE REVIEW

**Comment by remi6397** [comment]
While I agree that we should search both for ``rake`` and Ruby to increase code *readability*, I would advise you to consider marking Ruby as required on **all compatible platforms**, because making it optional will probably result in incompatibility between custom and official builds and discourage potential contributors from improving our MRuby API.

If you still insist on making Ruby a second-class citizen, you should also move associated [fallback clauses](https://github.com/remi6397/TIC-80/blob/a7990161f1196dbf3040e6eb78513172c3ef20d1/src/console.c#L68) to the bottom. 😞

**Comment by RobLoach** [comment]
I do not mean to make Ruby is not a second class citizen... Ruby is just not available everywhere where TIC-80 is built. If we add Ruby as a dependency to build TIC-80, it will mean breaking compilation for older platforms. I would absolutely love for it to be available everywhere.

I see an old PR to add CMake support, and can understand why they chose to roll with Rake instead of CMake. Wonder if there could be a way to get that up and running again.

**Comment by remi6397** [comment]
If we want to support ancient systems that Ruby isn't available on, everything seems reasonable to me then. 😄

But there are still those fallback clauses in e.g. ``console.c``. Shall we leave them in current order, or rather move them to the bottom-most position?

**Comment by remi6397** [comment]
No objections then? In that case, I'm merging this very patch.

**Comment by RobLoach** [comment]
Thanks for the merge, there's certainly a few changes and clean up we could do upon this too, so thanks for adapting.

>  Shall we leave them in current order, or rather move them to the bottom-most position?

Either order is good :wink:

**Pull request merged**
